# Make sure to check the documentation at http://goreleaser.com

before:
  hooks:
  - go vet ./...
  - go test --cover ./...

builds:
- env:
  - CGO_ENABLED=0 # this is needed otherwise the Docker image build is faulty
  goarch:
  - amd64
  - arm
  - arm64
  - 386
  goos:
  - linux
  - darwin
  goarm:
  - 7

archives:
- format: binary
  name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

dockers:
- image_templates:
  - "docker.io/appuio/image-cleanup:v{{ .Version }}"
  - "docker.io/appuio/image-cleanup:v{{ .Major }}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^Docs:'
    - '^Test:'
    - '^Refactor:'

release:
  github:
    owner: appuio
    name: image-cleanup
