---
name: Release

on:
  push:
    branches:
    - master
    tags:
    - "*"

env:
  REGISTRY_IMAGE: docker.io/appuio/image-cleanup

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    #- name: Lint YAML files
    #  run: docker run --rm -v $(pwd):/data docker.io/cytopia/yamllint .

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: /home/runner/go/pkg/mod
        key: go-mod
    - name: Run unit tests
      run: go test ./...

  release:
    runs-on: ubuntu-latest
    needs:
    - lint
    - test
    if: github.ref != 'refs/heads/master'
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: /home/runner/go/pkg/mod
        key: go-mod
    - name: Login to Docker hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - uses: goreleaser/goreleaser-action@v1
      with:
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
